development:
  adapter: postgresql
  encoding: unicode
  database: PORT_development
  pool: 5
  username: postgres
  password: julia
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: PORT_test
  pool: 5
  username: postgres
  password: julia
